[build]
  command = "cd chess-frontend && npm install && npm run build && cd .. && mkdir -p public && cp -r chess-frontend/public/* public/ && mkdir -p public/api/auth public/api/games"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "your-super-secret-jwt-key-change-in-production"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/health"
  status = 200
  to = "/api/health.json"

[[redirects]]
  from = "/api/auth/register"
  status = 200
  to = "/api/auth/register.json"

[[redirects]]
  from = "/api/auth/login"
  status = 200
  to = "/api/auth/login.json"

[[redirects]]
  from = "/api/games"
  status = 200
  to = "/api/games/index.json"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"